name: Build WebApp

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npm run build

      - name: Install mklittlefs
        run: |
          wget https://github.com/earlephilhower/mklittlefs/releases/latest/download/mklittlefs-linux-x86_64.tar.gz
          tar -xzf mklittlefs-linux-x86_64.tar.gz

      - name: Create LittleFS image
        run: |
          ./mklittlefs \
            -c dist \
            -s 1572864 \
            littlefs.bin

      - uses: actions/upload-artifact@v4
        with:
          name: littlefs
          path: littlefs.bin

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
